semanticGroupTypeDict={
	52:{'name':'Activity','group':'Activities & Behaviors'},
	53:{'name':'Behavior','group':'Activities & Behaviors'},
	56:{'name':'Daily or Recreational Activity','group':'Activities & Behaviors'},
	51:{'name':'Event','group':'Activities & Behaviors'},
	64:{'name':'Governmental or Regulatory Activity','group':'Activities & Behaviors'},
	55:{'name':'Individual Behavior','group':'Activities & Behaviors'},
	66:{'name':'Machine Activity','group':'Activities & Behaviors'},
	57:{'name':'Occupational Activity','group':'Activities & Behaviors'},
	54:{'name':'Social Behavior','group':'Activities & Behaviors'},
	17:{'name':'Anatomical Structure','group':'Anatomy'},
	29:{'name':'Body Location or Region','group':'Anatomy'},
	23:{'name':'Body Part, Organ, or Organ Component','group':'Anatomy'},
	30:{'name':'Body Space or Junction','group':'Anatomy'},
	31:{'name':'Body Substance','group':'Anatomy'},
	22:{'name':'Body System','group':'Anatomy'},
	25:{'name':'Cell','group':'Anatomy'},
	26:{'name':'Cell Component','group':'Anatomy'},
	18:{'name':'Embryonic Structure','group':'Anatomy'},
	21:{'name':'Fully Formed Anatomical Structure','group':'Anatomy'},
	24:{'name':'Tissue','group':'Anatomy'},
	116:{'name':'Amino Acid, Peptide, or Protein','group':'Genes & Molecular Sequences'},
	195:{'name':'Antibiotic','group':'Chemicals & Drugs'},
	123:{'name':'Biologically Active Substance','group':'Chemicals & Drugs'},
	122:{'name':'Biomedical or Dental Material','group':'Chemicals & Drugs'},
	118:{'name':'Carbohydrate','group':'Chemicals & Drugs'},
	103:{'name':'Chemical','group':'Chemicals & Drugs'},
	120:{'name':'Chemical Viewed Functionally','group':'Chemicals & Drugs'},
	104:{'name':'Chemical Viewed Structurally','group':'Chemicals & Drugs'},
	200:{'name':'Clinical Drug','group':'Chemicals & Drugs'},
	111:{'name':'Eicosanoid','group':'Chemicals & Drugs'},
	196:{'name':'Element, Ion, or Isotope','group':'Chemicals & Drugs'},
	126:{'name':'Enzyme','group':'Chemicals & Drugs'},
	131:{'name':'Hazardous or Poisonous Substance','group':'Chemicals & Drugs'},
	125:{'name':'Hormone','group':'Chemicals & Drugs'},
	129:{'name':'Immunologic Factor','group':'Chemicals & Drugs'},
	130:{'name':'Indicator, Reagent, or Diagnostic Aid','group':'Chemicals & Drugs'},
	197:{'name':'Inorganic Chemical','group':'Chemicals & Drugs'},
	119:{'name':'Lipid','group':'Chemicals & Drugs'},
	124:{'name':'Neuroreactive Substance or Biogenic Amine','group':'Chemicals & Drugs'},
	114:{'name':'Nucleic Acid, Nucleoside, or Nucleotide','group':'Chemicals & Drugs'},
	109:{'name':'Organic Chemical','group':'Chemicals & Drugs'},
	115:{'name':'Organophosphorus Compound','group':'Chemicals & Drugs'},
	121:{'name':'Pharmacologic Substance','group':'Chemicals & Drugs'},
	192:{'name':'Receptor','group':'Chemicals & Drugs'},
	110:{'name':'Steroid','group':'Chemicals & Drugs'},
	127:{'name':'Vitamin','group':'Chemicals & Drugs'},
	185:{'name':'Classification','group':'Concepts & Ideas'},
	77:{'name':'Conceptual Entity','group':'Concepts & Ideas'},
	169:{'name':'Functional Concept','group':'Concepts & Ideas'},
	102:{'name':'Group Attribute','group':'Concepts & Ideas'},
	78:{'name':'Idea or Concept','group':'Concepts & Ideas'},
	170:{'name':'Intellectual Product','group':'Concepts & Ideas'},
	171:{'name':'Language','group':'Concepts & Ideas'},
	80:{'name':'Qualitative Concept','group':'Concepts & Ideas'},
	81:{'name':'Quantitative Concept','group':'Concepts & Ideas'},
	89:{'name':'Regulation or Law','group':'Concepts & Ideas'},
	82:{'name':'Spatial Concept','group':'Concepts & Ideas'},
	79:{'name':'Temporal Concept','group':'Concepts & Ideas'},
	203:{'name':'Drug Delivery Device','group':'Devices'},
	74:{'name':'Medical Device','group':'Devices'},
	75:{'name':'Research Device','group':'Devices'},
	20:{'name':'Acquired Abnormality','group':'Diseases & Disorders'},
	190:{'name':'Anatomical Abnormality','group':'Diseases & Disorders'},
	49:{'name':'Cell or Molecular Dysfunction','group':'Diseases & Disorders'},
	19:{'name':'Congenital Abnormality','group':'Diseases & Disorders'},
	47:{'name':'Disease or Syndrome','group':'Diseases & Disorders'},
	50:{'name':'Experimental Model of Disease','group':'Diseases & Disorders'},
	33:{'name':'Finding','group':'Others'},
#	33:{'name':'Finding','group':'Diseases & Disorders'},
	37:{'name':'Injury or Poisoning','group':'Diseases & Disorders'},
	48:{'name':'Mental or Behavioral Dysfunction','group':'Diseases & Disorders'},
	191:{'name':'Neoplastic Process','group':'Diseases & Disorders'},
	46:{'name':'Pathologic Function','group':'Diseases & Disorders'},
	184:{'name':'Sign or Symptom','group':'Diseases & Disorders'},
	87:{'name':'Amino Acid Sequence','group':'Genes & Molecular Sequences'},
	88:{'name':'Carbohydrate Sequence','group':'Genes & Molecular Sequences'},
	28:{'name':'Gene or Genome','group':'Genes & Molecular Sequences'},
	85:{'name':'Molecular Sequence','group':'Genes & Molecular Sequences'},
	86:{'name':'Nucleotide Sequence','group':'Genes & Molecular Sequences'},
	83:{'name':'Geographic Area','group':'Geographic Areas'},
	100:{'name':'Age Group','group':'Living Beings'},
	3:{'name':'Alga','group':'Living Beings'},
	11:{'name':'Amphibian','group':'Living Beings'},
	8:{'name':'Animal','group':'Living Beings'},
	194:{'name':'Archaeon','group':'Living Beings'},
	7:{'name':'Bacterium','group':'Living Beings'},
	12:{'name':'Bird','group':'Living Beings'},
	99:{'name':'Family Group','group':'Living Beings'},
	13:{'name':'Fish','group':'Living Beings'},
	4:{'name':'Fungus','group':'Living Beings'},
	96:{'name':'Group','group':'Living Beings'},
	16:{'name':'Human','group':'Living Beings'},
	9:{'name':'Invertebrate','group':'Living Beings'},
	15:{'name':'Mammal','group':'Living Beings'},
	1:{'name':'Organism','group':'Living Beings'},
	101:{'name':'Patient or Disabled Group','group':'Living Beings'},
	2:{'name':'Plant','group':'Living Beings'},
	98:{'name':'Population Group','group':'Living Beings'},
	97:{'name':'Professional or Occupational Group','group':'Living Beings'},
	14:{'name':'Reptile','group':'Living Beings'},
	6:{'name':'Rickettsia or Chlamydia','group':'Living Beings'},
	10:{'name':'Vertebrate','group':'Living Beings'},
	5:{'name':'Virus','group':'Living Beings'},
	71:{'name':'Entity','group':'Objects'},
	168:{'name':'Food','group':'Objects'},
	73:{'name':'Manufactured Object','group':'Objects'},
	72:{'name':'Physical Object','group':'Objects'},
	167:{'name':'Substance','group':'Objects'},
	91:{'name':'Biomedical Occupation or Discipline','group':'Occupations'},
	90:{'name':'Occupation or Discipline','group':'Occupations'},
	93:{'name':'Health Care Related Organization','group':'Organizations'},
	92:{'name':'Organization','group':'Organizations'},
	94:{'name':'Professional Society','group':'Organizations'},
	95:{'name':'Self-help or Relief Organization','group':'Organizations'},
	38:{'name':'Biologic Function','group':'Phenomena'},
	69:{'name':'Environmental Effect of Humans','group':'Phenomena'},
	68:{'name':'Human-caused Phenomenon or Process','group':'Phenomena'},
	34:{'name':'Laboratory or Test Result','group':'Phenomena'},
	70:{'name':'Natural Phenomenon or Process','group':'Phenomena'},
	67:{'name':'Phenomenon or Process','group':'Phenomena'},
	43:{'name':'Cell Function','group':'Physiology'},
	201:{'name':'Clinical Attribute','group':'Physiology'},
	45:{'name':'Genetic Function','group':'Physiology'},
	41:{'name':'Mental Process','group':'Physiology'},
	44:{'name':'Molecular Function','group':'Physiology'},
	42:{'name':'Organ or Tissue Function','group':'Physiology'},
	32:{'name':'Organism Attribute','group':'Physiology'},
	40:{'name':'Organism Function','group':'Physiology'},
	39:{'name':'Physiologic Function','group':'Physiology'},
	60:{'name':'Diagnostic Procedure','group':'Procedures'},
	65:{'name':'Educational Activity','group':'Procedures'},
	58:{'name':'Health Care Activity','group':'Procedures'},
	59:{'name':'Laboratory Procedure','group':'Procedures'},
	63:{'name':'Molecular Biology Research Technique','group':'Procedures'},
	62:{'name':'Research Activity','group':'Procedures'},
	61:{'name':'Therapeutic or Preventive Procedure','group':'Procedures'},
}
